### PR TITLE
add dark mode compatibility

### PR DESCRIPTION
**Pull request by FrederikBornemann**
This adds dark mode panel icons to the homepage. The image sources are being changed by a script when a theme switch occurs.

image

### CODE REVIEW

**Comment by FrederikBornemann** [comment]
Since the toc of the user guide also needs an update for dark mode, I would convert this PR to a draft and work on that.
image

**Comment by MalteKurz** [comment]
> Since the toc of the user guide also needs an update for dark mode, I would convert this PR to a draft and work on that.
Sounds good, thank you :+1:

**Comment by FrederikBornemann** [comment]
The user guide toc dark mode now looks like this: 
image

**Review by MalteKurz — APPROVED** [review]
Thanks a lot for fixing the dark mode.

**Pull request merged**
